version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
