name: doxygen-ghpages
env:
  ISPN_VER: '13.0.5.Final'
on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    env:
       HAVE_DOTNET_TOKEN: ${{ secrets.DOTNETCLIENT_PERSONAL_TOKEN != '' }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        if: ${{ env.HAVE_DOTNET_TOKEN == 'true' }}
      - uses: mattnotmitt/doxygen-action@592353912f380a976df0007746e939a002cabae2 # v1.9.2
        if: ${{ env.HAVE_DOTNET_TOKEN == 'true' }}
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        if: ${{ env.HAVE_DOTNET_TOKEN == 'true' }}
        with:
          personal_token: ${{ secrets.DOTNETCLIENT_PERSONAL_TOKEN }}
          publish_dir: ./docs
          external_repository: rigazilla/Infinispan.Hotrod.Core
